require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/AbcSize:
  Exclude:
    - 'lib/**/*.rb'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/**/*.rb'
Metrics/MethodLength:
  Exclude:
    - 'lib/**/*.rb'
Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/**/*.rb'
Layout/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 250
RSpec/Be:
  Exclude:
    - 'spec/**/*.rb'
RSpec/ExampleLength:
  Max: 6
RSpec/MultipleMemoizedHelpers:
  Max: 7
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NotToNot:
  Exclude:
    - 'spec/**/*.rb'
